version: '3'
services:
  beemon:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    working_dir: /app
    environment:
      PYTHONDONTWRITEBYTECODE: 1
      PYTHONUNBUFFERED: 1
    command: python run.py

  # Outros serviços podem ser adicionados aqui, se necessário

