# This is a basic workflow to help you get started with Actions

name: CI-Django

# Controls when the workflow will run
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Check out code
        uses: actions/checkout@v3
    
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Update pip
        run: pip install --upgrade pip
        
      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Apply Django Migrations
        run: python manage.py migrate
    
      - name: Run Django tests
        run: python manage.py test



